# Generated by Django 4.1.5 on 2023-03-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=150)),
                ('Second_name', models.CharField(max_length=150)),
                ('Phone_number', models.CharField(max_length=12)),
                ('ID_number', models.PositiveIntegerField()),
                ('ID_front', models.FileField(null=True, upload_to='media')),
                ('ID_back', models.FileField(null=True, upload_to='media')),
                ('Signed_contract', models.FileField(null=True, upload_to='media')),
            ],
        ),
    ]
