# Generated by Django 4.1.5 on 2023-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='ID_back',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ID_front',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='Signed_contract',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
