# Generated by Django 4.1.5 on 2023-03-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
