# Generated by Django 4.1.5 on 2023-02-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='tenant',
        ),
    ]
