# Generated by Django 4.1.5 on 2023-03-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='consumption',
            field=models.PositiveIntegerField(default=22),
            preserve_default=False,
        ),
    ]
