# Generated by Django 4.1.5 on 2023-03-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_meterreading_consumption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
