# Generated by Django 4.1.5 on 2023-04-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_meterreading_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='Cost',
            new_name='cost',
        ),
    ]
