# Generated by Django 4.1.5 on 2023-04-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_rename_cost_meterreading_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterreading',
            name='previous_reading',
        ),
    ]
