# Generated by Django 4.1.5 on 2023-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_remove_meterreading_previous_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
