# Generated by Django 4.1.5 on 2023-04-05 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_alter_meterreading_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utility_payments', to='houses.house')),
            ],
        ),
    ]
