# Generated by Django 4.1.5 on 2023-03-21 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('occupation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tenant',
        ),
        migrations.AddField(
            model_name='payment',
            name='occupation',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.CASCADE, to='occupation.occupation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
